# Common configuration
spring:
  application:
    name: deliver-backend
  
  profiles:
    active: dev

  jpa:
    hibernate:
  ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: deliver.backend.app@gmail.com
    password: chyoxufxhpxjgwkw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp

# Server configuration
server:
  port: 8080

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info
